export const HEADER_VALUES: Record<string, string | string[]> = {
    'Accept': ['*/*', 'application/json', 'text/html', 'application/xml'],
    'Accept-Charset': ['utf-8', 'iso-8859-1'],
    'Accept-Encoding': ['gzip', 'deflate', 'br'],
    'Accept-Language': ['en-US', 'en', 'es-ES', 'fr-FR'],
    'Accept-Patch': ['application/json-patch+json'],
    'Accept-Ranges': ['bytes', 'none'],
    'Access-Control-Allow-Credentials': ['true', 'false'],
    'Access-Control-Allow-Headers': ['Content-Type', 'Authorization', 'X-Requested-With'],
    'Access-Control-Allow-Methods': ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    'Access-Control-Allow-Origin': ['*', 'https://example.com'],
    'Access-Control-Expose-Headers': ['Content-Length', 'X-Kuma-Revision'],
    'Access-Control-Max-Age': 'number (seconds)',
    'Access-Control-Request-Headers': ['X-PINGOTHER', 'Content-Type'],
    'Access-Control-Request-Method': ['GET', 'POST', 'PUT', 'DELETE'],
    'Allow': ['GET', 'POST', 'OPTIONS'],
    'Authorization': 'Bearer <token> or Basic <base64-credentials>',
    'Cache-Control': ['no-cache', 'no-store', 'max-age=3600', 'must-revalidate'],
    'Clear-Site-Data': ['"cache"', '"cookies"', '"storage"', '"executionContexts"'],
    'Connection': ['keep-alive', 'close'],
    'Content-Disposition': ['inline', 'attachment; filename="file.txt"'],
    'Content-Encoding': ['gzip', 'compress', 'deflate', 'br'],
    'Content-Language': ['en', 'en-US', 'es'],
    'Content-Length': 'number (bytes)',
    'Content-Location': 'URL or path',
    'Content-Security-Policy': ['default-src "self"', 'script-src "none"'],
    'Content-Type': ['application/json', 'text/plain', 'application/x-www-form-urlencoded', 'multipart/form-data'],
    'Cookie': 'key=value; key2=value2',
    'Date': 'HTTP-date (e.g. Tue, 15 Nov 1994 08:12:31 GMT)',
    'ETag': 'etag-string (e.g. "abc123", W/"xyz789")',
    'Expect': ['100-continue'],
    'Forwarded': 'for=ip; proto=http; by=ip',
    'Host': 'domain.com or domain.com:port',
    'If-Match': '"etag"',
    'If-Modified-Since': 'HTTP-date',
    'If-None-Match': '"etag"',
    'If-Range': '"etag" or HTTP-date',
    'If-Unmodified-Since': 'HTTP-date',
    'Last-Modified': 'HTTP-date',
    'Link': '<https://example.com>; rel="preconnect"',
    'Origin': 'https://example.com',
    'Pragma': ['no-cache'],
    'Proxy-Authenticate': 'auth-scheme realm',
    'Proxy-Authorization': 'Basic <base64-credentials>',
    'Range': 'bytes=0-499 or bytes=500-999',
    'Referer': 'URL',
    'Retry-After': 'seconds or HTTP-date',
    'Server': ['nginx', 'Apache', 'Cloudflare'],
    'Set-Cookie': 'Set-Cookie string (e.g. sessionId=abc123; Path=/; HttpOnly)',
    'Strict-Transport-Security': ['max-age=31536000', 'includeSubDomains'],
    'TE': ['trailers', 'deflate'],
    'Trailer': ['Expires', 'Content-MD5'],
    'Transfer-Encoding': ['chunked'],
    'Upgrade': ['websocket', 'h2c'],
    'User-Agent': 'User agent string (e.g. Mozilla/5.0, curl/7.64.1)',
    'Vary': ['Accept-Encoding', 'Origin'],
    'Via': '1.1 vegur or proxy chain',
    'Warning': '199 Miscellaneous warning',
    'WWW-Authenticate': ['Basic realm="Access to site"', 'Bearer'],
    'X-Content-Type-Options': ['nosniff'],
    'X-Forwarded-For': 'IP address',
    'X-Forwarded-Host': 'host name',
    'X-Forwarded-Proto': ['http', 'https'],
    'X-Frame-Options': ['DENY', 'SAMEORIGIN'],
    'X-Requested-With': ['XMLHttpRequest'],
    'X-XSS-Protection': ['1; mode=block']
}
