name: CI (tests and build)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './app/'

      - name: Install dependencies
        working-directory: ./app 
        run: npm ci
      
      - name: Run tests
        working-directory: ./app 
        run: npm run test

      - name: Build
        working-directory: ./app
        run: npm run build