name: CI (tests and build)

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './app/'

      - name: Install dependencies
        working-directory: ./app 
        run: npm ci
      
      - name: Audit Dependencies for Vulnerabilities
        run: |
          audit_output=$(npm audit --json)
          low=$(echo "$audit_output" | jq '.metadata.vulnerabilities.low')
          moderate=$(echo "$audit_output" | jq '.metadata.vulnerabilities.moderate')
          high=$(echo "$audit_output" | jq '.metadata.vulnerabilities.high')
          critical=$(echo "$audit_output" | jq '.metadata.vulnerabilities.critical')

          echo "Vulnerabilities - Low: $low, Moderate: $moderate, High: $high, Critical: $critical"

          if [ "$moderate" -gt 0 ] || [ "$high" -gt 0 ] || [ "$critical" -gt 0 ]; then
            echo -e "${RED} High level vulnerabilities found. Failing the job."
            exit 1
          else
            echo -e "${GREEN} No vulnerabilities found."
          fi
        working-directory: app
            
      - name: Run tests
        working-directory: ./app 
        run: npm run test

      - name: Build
        working-directory: ./app
        run: npm run build